"""Add Vacation table

Revision ID: ad31994a0b36
Revises: 27bf2aa3b8c7
Create Date: 2025-03-23 03:46:51.253648

"""

from alembic import op
import sqlalchemy as sa

from app.model.base import CustomUUID

# revision identifiers, used by Alembic.
revision = "ad31994a0b36"
down_revision = "27bf2aa3b8c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacation",
        sa.Column("employee_id", CustomUUID(), nullable=False),
        sa.Column(
            "type",
            sa.SmallInteger(),
            nullable=False,
            comment="Vacation type: 0 = Unpaid, 1 = Paid",
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("id", CustomUUID(), nullable=False),
        sa.CheckConstraint("type IN (0, 1)", name="check_vacation_type"),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vacation_id"), "vacation", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vacation_id"), table_name="vacation")
    op.drop_table("vacation")
    # ### end Alembic commands ###
